application: hime
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: smth.py

- url: /static
  static_dir: static

- url: /(ipad|smth|board|subject|post|ipost|isubject|iboard)/.*
  script: smth.py

- url: /(jj|jjboard|jjsubject)/.*
  script: jj.py


skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
