application: hime
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: smth.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(apple-touch-icon-precomposed.png|apple-touch-icon.png)
  static_files: static/favicon.png
  upload: static/favicon.png  

- url: /(ipad|smth|board|subject|post|ipost|isubject|iboard|config)/.*
  script: smth.py

- url: /(jj|jjboard|jjsubject)/.*
  script: jj.py


skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*\Thumbs.db)|
 )$
